import { StyleSheet } from "react-native";

export const GetStarterStyles = StyleSheet.create({
  comecar1FlexBox: {
    textAlign: "center",
    position: "absolute",
  },
  naPalmaDaTypo: {
    fontFamily: "Poppins-Bold",
    fontWeight: "700",
  },
  barFlexBox: {
    justifyContent: "center",
    flexDirection: "row",
  },
  notchLayout: {
    width: 172,
    overflow: "hidden",
  },
  iconLayout: {
    height: 12,
    width: 18,
  },
  iconSpaceBlock: {
    marginLeft: 8,
    overflow: "hidden",
  },
  imageBackgroundIcon: {
    top: -48,
    left: -39,
    width: 527,
    height: 682,
    position: "absolute",
  },
  dogAndHumanImg: {
    top: 146,
    left: -18,
    width: 464,
    height: 379,
    position: "absolute",
  },
  rectangle: {
    top: 500,
    left: -178,
    borderTopLeftRadius: 500,
    borderTopRightRadius: 500,
    borderBottomRightRadius: 50,
    borderBottomLeftRadius: 50,
    width: 784,
    height: 426,
    position: "absolute",
    backgroundColor: "#fff",
  },
  rectangle1: {
    left: 0,
    borderRadius: 50,
    backgroundColor: "#50808e",
    top: 0,
    height: 70,
    width: 290,
    position: "absolute",
  },
  comear1: {
    top: 17,
    left: 87,
    fontSize: 24,
    fontWeight: "600",
    fontFamily: "Poppins-SemiBold",
    color: "#fff",
  },
  comear: {
    top: 779,
    height: 70,
    width: 290,
    left: 60,
    position: "absolute",
  },
  bemEstarAnimal: {
    fontWeight: "500",
    fontFamily: "Poppins-Medium",
    color: "#949494",
  },
  naPalmaDa: {
    color: "#50808e",
  },
  bemEstarAnimalNaContainer: {
    top: 672,
    fontSize: 18,
    width: 290,
    left: 60,
    textAlign: "center",
  },
  amorECuidado: {
    top: 564,
    left: 80,
    fontSize: 28,
    color: "#464646",
    width: 250,
    textAlign: "center",
    position: "absolute",
  },
  emojiPatasIcon: {
    top: 102,
    left: 150,
    width: 64,
    height: 64,
    position: "absolute",
    overflow: "hidden",
  },
  pawsitiveCare: {
    top: 62,
    left: 33,
    fontSize: 36,
    letterSpacing: 3.6,
    textAlign: "left",
    color: "#fff",
    position: "absolute",
  },
  timeIcon: {
    width: 40,
    height: 13,
    overflow: "hidden",
  },
  time: {
    alignSelf: "stretch",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    overflow: "hidden",
    backgroundColor: "rgba(255, 255, 255, 0.8)",
    flex: 1,
  },
  notchIcon: {
    height: 32,
  },
  notchFrame: {
    justifyContent: "center",
    flexDirection: "row",
    width: 172,
    height: 47,
    backgroundColor: "rgba(255, 255, 255, 0.8)",
  },
  receptionIcon: {
    overflow: "hidden",
  },
  wiFiIcon: {
    height: 12,
    width: 18,
  },
  batteryIcon: {
    width: 28,
    height: 13,
  },
  statusBar: {
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    overflow: "hidden",
    height: 47,
    backgroundColor: "rgba(255, 255, 255, 0.8)",
    left: "0%",
    right: "0%",
    top: 0,
    position: "absolute",
    width: "100%",
  },
  rectangle2: {
    borderRadius: 3,
    backgroundColor: "#000",
    width: 134,
    height: 5,
  },
  homeBar: {
    top: 892,
    backgroundColor: "rgba(255, 255, 255, 0)",
    height: 34,
    paddingTop: 13,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    overflow: "hidden",
    left: "0%",
    right: "0%",
    position: "absolute",
    width: "100%",
  },
  getStarted: {
    borderRadius: 30,
    height: 926,
    overflow: "hidden",
    width: "100%",
    flex: 1,
    backgroundColor: "#50808e",
  },
});

export default GetStarterStyles;