import { StyleSheet } from "react-native";

export const ResetPasswordStyles = StyleSheet.create({
  primaryButton: {
    borderRadius: 50,
    backgroundColor: "#50808e",
    flex: 1,
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 15,
    paddingVertical: 20,
  },
  input1: {
    top: 150,
    borderStyle: "solid",
    borderColor: "#e2e2e2",
    borderWidth: 1,
    width: 395,
    paddingHorizontal: 24,
    paddingVertical: 15,
    alignItems: "center",
    flexDirection: "row",
    left: 16,
    position: "absolute",
    borderRadius: 30,
  },
  input2: {
    top: 230,
    borderStyle: "solid",
    borderColor: "#e2e2e2",
    borderWidth: 1,
    width: 395,
    paddingHorizontal: 24,
    paddingVertical: 15,
    alignItems: "center",
    flexDirection: "row",
    left: 16,
    position: "absolute",
    borderRadius: 30,
  },
  rectangle: {
    borderRadius: 50,
    backgroundColor: "#50808e",
    left: 0,
    top: 0,
    height: 70,
    width: 290,
    position: "absolute",
  },
  button: {
    top: 17,
    left: 100,
    textAlign: "center",
    color: "#fff",
    fontFamily: "Poppins-SemiBold",
    fontWeight: "600",
    fontSize: 24,
    position: "absolute",
  },
  pageTitle: {
    marginLeft: 120,
    fontSize: 32,
    letterSpacing: 1,
    lineHeight: 28,
    color: "#2a2a2a",
    top: 60,
  },
  comear: {
    top: 350,
    left: 69,
    height: 70,
    width: 290,
    position: "absolute",
  },
});

export default ResetPasswordStyles;
