import { StyleSheet } from "react-native";

const SplashPageStyle = StyleSheet.create({
    umaPosition: {
        left: "50%",
        position: "absolute",
      },
      rectangleLayout: {
        borderRadius: 50,
        top: 0,
        height: 70,
        left: 0,
        width: 290,
        position: "absolute",
      },
      textTypo: {
        color: "#fff",
        fontFamily: "Poppins-SemiBold",
        fontSize: 24,
        top: 17,
        textAlign: "center",
        fontWeight: "600",
        position: "absolute",
      },
      barFlexBox: {
        justifyContent: "center",
        flexDirection: "row",
      },
      notchLayout: {
        width: 172,
        overflow: "hidden",
      },
      iconLayout: {
        height: 12,
        width: 18,
      },
      iconSpaceBlock: {
        marginLeft: 8,
        overflow: "hidden",
      },
      poweredByIpb: {
        marginLeft: -84,
        bottom: 34,
        fontFamily: "Inter-SemiBold",
        color: "#928f9a",
        width: 168,
        height: 26,
        textAlign: "center",
        fontWeight: "600",
        fontSize: 16,
        left: "50%",
        position: "absolute",
      },
      logoIcon: {
        height: "4.32%",
        marginLeft: -20,
        top: "86.5%",
        bottom: "9.18%",
        maxHeight: "100%",
        width: 40,
      },
      jTemUma: {
        color: "#696969",
        fontFamily: "Poppins-Regular",
      },
      entrar: {
        fontWeight: "900",
        fontFamily: "Poppins-Black",
        color: "#50808e",
      },
      text: {
        marginLeft: -112,
        letterSpacing: 0.2,
        lineHeight: 26,
        textAlign: "center",
        fontSize: 16,
      },
      jTemUmaContainer: {
        top: 734,
      },
      rectangle: {
        backgroundColor: "#50808e",
      },
      text1: {
        left: 101,
      },
      cliente: {
        top: 140,
        height: 70,
        left: 0,
        width: 290,
        position: "absolute",
      },
      rectangle1: {
        backgroundColor: "#28c047",
      },
      text2: {
        left: 55,
      },
      administrador: {
        top: 0,
        height: 70,
        left: 0,
        width: 290,
        position: "absolute",
      },
      botes: {
        top: 288,
        left: 69,
        height: 210,
        width: 290,
        position: "absolute",
      },
      escolhaUmaOpo: {
        marginLeft: -167,
        top: 60,
        fontSize: 32,
        letterSpacing: 1,
        lineHeight: 28,
        color: "#2a2a2a",
        fontFamily: "Poppins-Regular",
        textAlign: "center",
      },
      timeIcon: {
        height: 13,
        width: 40,
        overflow: "hidden",
      },
      time: {
        alignSelf: "stretch",
        alignItems: "center",
        justifyContent: "center",
        flexDirection: "row",
        overflow: "hidden",
        backgroundColor: "rgba(255, 255, 255, 0.8)",
        flex: 1,
      },
      notchIcon: {
        height: 32,
      },
      notchFrame: {
        justifyContent: "center",
        flexDirection: "row",
        width: 172,
        height: 47,
        backgroundColor: "rgba(255, 255, 255, 0.8)",
      },
      receptionIcon: {
        overflow: "hidden",
      },
      wiFiIcon: {
        height: 12,
        width: 18,
      },
      batteryIcon: {
        width: 28,
        height: 13,
      },
      statusBar: {
        alignItems: "center",
        justifyContent: "center",
        flexDirection: "row",
        overflow: "hidden",
        height: 47,
        backgroundColor: "rgba(255, 255, 255, 0.8)",
        left: "0%",
        right: "0%",
        top: 0,
        position: "absolute",
        width: "100%",
      },
      rectangle2: {
        borderRadius: 3,
        backgroundColor: "#000",
        width: 134,
        height: 5,
      },
      homeBar: {
        top: 892,
        backgroundColor: "rgba(255, 255, 255, 0)",
        height: 34,
        paddingTop: 13,
        alignItems: "center",
        justifyContent: "center",
        flexDirection: "row",
        overflow: "hidden",
        left: "0%",
        right: "0%",
        position: "absolute",
        width: "100%",
      },
      splashPage: {
        borderRadius: 30,
        backgroundColor: "#fff",
        height: 926,
        overflow: "hidden",
        width: "100%",
        flex: 1,
      },
});

export default SplashPageStyle